bridge_port = 8031

[persistence]
path = "/data/local/uplink/persistence"
max_file_size = 104857600
max_file_count = 3

[downloader]
actions = ["update_firmware"]
path = "/data/local/uplink/ota"

[stats]
enabled = true
process_names = ["io.bytebeam.android_web_wrapper"]
update_period = 5
stream_size = 1

[logging]
tags = ["*"]
min_level = 6