name: Build and release uplink-android packages
on:
  release:
    types: [published]

jobs:
  build-release:
    name: Build release
    runs-on: ubuntu-latest
    container:
      image: bytebeamio/rust-android
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build with gradle
        run: JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ ./gradlew :buildArtifacts

      - name: Upload release archive
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/release/*.tar.gz
            build/release/uplink_*.aar
  
